/**
 * This class is generated by jOOQ
 */
package facebook.lead.push.by.pageid.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Facebookleadpush extends org.jooq.impl.TableImpl<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> {

	private static final long serialVersionUID = 1717208728;

	/**
	 * The singleton instance of <code>public.FacebookLeadPush</code>
	 */
	public static final facebook.lead.push.by.pageid.tables.Facebookleadpush FACEBOOKLEADPUSH = new facebook.lead.push.by.pageid.tables.Facebookleadpush();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> getRecordType() {
		return facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord.class;
	}

	/**
	 * The column <code>public.FacebookLeadPush.page_id</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> PAGE_ID = createField("page_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.lead_id</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> LEAD_ID = createField("lead_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.form_id</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> FORM_ID = createField("form_id", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.customer</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> CUSTOMER = createField("customer", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.webform_id</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> WEBFORM_ID = createField("webform_id", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.full_name</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> FULL_NAME = createField("full_name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.when_are_you_planning_to_make_a_purchase</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> WHEN_ARE_YOU_PLANNING_TO_MAKE_A_PURCHASE = createField("when_are_you_planning_to_make_a_purchase", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.phone_number</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> PHONE_NUMBER = createField("phone_number", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.email</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.FacebookLeadPush.created_time</code>.
	 */
	public final org.jooq.TableField<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord, java.lang.String> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.FacebookLeadPush</code> table reference
	 */
	public Facebookleadpush() {
		this("FacebookLeadPush", null);
	}

	/**
	 * Create an aliased <code>public.FacebookLeadPush</code> table reference
	 */
	public Facebookleadpush(java.lang.String alias) {
		this(alias, facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH);
	}

	private Facebookleadpush(java.lang.String alias, org.jooq.Table<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> aliased) {
		this(alias, aliased, null);
	}

	private Facebookleadpush(java.lang.String alias, org.jooq.Table<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, facebook.lead.push.by.pageid.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> getPrimaryKey() {
		return facebook.lead.push.by.pageid.Keys.FACEBOOK_LEAD_PUSH_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord>>asList(facebook.lead.push.by.pageid.Keys.FACEBOOK_LEAD_PUSH_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public facebook.lead.push.by.pageid.tables.Facebookleadpush as(java.lang.String alias) {
		return new facebook.lead.push.by.pageid.tables.Facebookleadpush(alias, this);
	}

	/**
	 * Rename this table
	 */
	public facebook.lead.push.by.pageid.tables.Facebookleadpush rename(java.lang.String name) {
		return new facebook.lead.push.by.pageid.tables.Facebookleadpush(name, null);
	}
}
