/**
 * This class is generated by jOOQ
 */
package facebook.lead.push.by.pageid;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> FACEBOOK_LEAD_PUSH_PKEY = UniqueKeys0.FACEBOOK_LEAD_PUSH_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> FACEBOOK_LEAD_PUSH_PKEY = createUniqueKey(facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH, facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.FORM_ID);
	}
}
