/**
 * This class is generated by jOOQ
 */
package facebook.lead.push.by.pageid.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacebookleadpushRecord extends org.jooq.impl.UpdatableRecordImpl<facebook.lead.push.by.pageid.tables.records.FacebookleadpushRecord> implements org.jooq.Record10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -421239994;

	/**
	 * Setter for <code>public.FacebookLeadPush.page_id</code>.
	 */
	public void setPageId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.page_id</code>.
	 */
	public java.lang.String getPageId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.lead_id</code>.
	 */
	public void setLeadId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.lead_id</code>.
	 */
	public java.lang.String getLeadId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.form_id</code>.
	 */
	public void setFormId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.form_id</code>.
	 */
	public java.lang.String getFormId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.customer</code>.
	 */
	public void setCustomer(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.customer</code>.
	 */
	public java.lang.String getCustomer() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.webform_id</code>.
	 */
	public void setWebformId(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.webform_id</code>.
	 */
	public java.lang.String getWebformId() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.full_name</code>.
	 */
	public void setFullName(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.full_name</code>.
	 */
	public java.lang.String getFullName() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.when_are_you_planning_to_make_a_purchase</code>.
	 */
	public void setWhenAreYouPlanningToMakeAPurchase(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.when_are_you_planning_to_make_a_purchase</code>.
	 */
	public java.lang.String getWhenAreYouPlanningToMakeAPurchase() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.phone_number</code>.
	 */
	public void setPhoneNumber(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.phone_number</code>.
	 */
	public java.lang.String getPhoneNumber() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.FacebookLeadPush.created_time</code>.
	 */
	public void setCreatedTime(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.FacebookLeadPush.created_time</code>.
	 */
	public java.lang.String getCreatedTime() {
		return (java.lang.String) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.PAGE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.LEAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.FORM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.CUSTOMER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.WEBFORM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.FULL_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.WHEN_ARE_YOU_PLANNING_TO_MAKE_A_PURCHASE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.PHONE_NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH.CREATED_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPageId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLeadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFormId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCustomer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getWebformId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFullName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getWhenAreYouPlanningToMakeAPurchase();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPhoneNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getCreatedTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value1(java.lang.String value) {
		setPageId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value2(java.lang.String value) {
		setLeadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value3(java.lang.String value) {
		setFormId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value4(java.lang.String value) {
		setCustomer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value5(java.lang.String value) {
		setWebformId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value6(java.lang.String value) {
		setFullName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value7(java.lang.String value) {
		setWhenAreYouPlanningToMakeAPurchase(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value8(java.lang.String value) {
		setPhoneNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value9(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord value10(java.lang.String value) {
		setCreatedTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FacebookleadpushRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10) {
		return this;
	}

	@Override
	public String component1() {
		return null;
	}

	@Override
	public String component2() {
		return null;
	}

	@Override
	public String component3() {
		return null;
	}

	@Override
	public String component4() {
		return null;
	}

	@Override
	public String component5() {
		return null;
	}

	@Override
	public String component6() {
		return null;
	}

	@Override
	public String component7() {
		return null;
	}

	@Override
	public String component8() {
		return null;
	}

	@Override
	public String component9() {
		return null;
	}

	@Override
	public String component10() {
		return null;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FacebookleadpushRecord
	 */
	public FacebookleadpushRecord() {
		super(facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH);
	}

	/**
	 * Create a detached, initialised FacebookleadpushRecord
	 */
	public FacebookleadpushRecord(java.lang.String pageId, java.lang.String leadId, java.lang.String formId, java.lang.String customer, java.lang.String webformId, java.lang.String fullName, java.lang.String whenAreYouPlanningToMakeAPurchase, java.lang.String phoneNumber, java.lang.String email, java.lang.String createdTime) {
		super(facebook.lead.push.by.pageid.tables.Facebookleadpush.FACEBOOKLEADPUSH);

		setValue(0, pageId);
		setValue(1, leadId);
		setValue(2, formId);
		setValue(3, customer);
		setValue(4, webformId);
		setValue(5, fullName);
		setValue(6, whenAreYouPlanningToMakeAPurchase);
		setValue(7, phoneNumber);
		setValue(8, email);
		setValue(9, createdTime);
	}
}
